baseURL = '/'
languageCode = 'en-us'
title = 'MIOI Blog'
theme = "hugo-theme-monochrome"
googleAnalytics = "G-8PPBKZ5GD1"

[params]
author = "Tom van Dinther"
enableCollapsibleTOC = true
usePrismJS = false

[build]
  writeStats = true

[markup.highlight]
codeFences = true
lineNos = true
